import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));

function readCollection(name) {
  return readdirSync(join(root, 'content', name))
    .filter(file => file.endsWith('.json'))
    .sort()
    .map(file => {
      const path = join(root, 'content', name, file);
      const value = JSON.parse(readFileSync(path, 'utf8'));
      if (!value || Array.isArray(value) || typeof value !== 'object') {
        throw new Error(`${path} must contain one object`);
      }
      return value;
    })
    .filter(item => item.published === true);
}

function byOrder(a, b) {
  return (a.order ?? 9999) - (b.order ?? 9999);
}

function uniqueIds(items, key, label) {
  const seen = new Set();
  for (const item of items) {
    if (typeof item[key] !== 'string' || !item[key].trim()) {
      throw new Error(`${label} has a missing ${key}`);
    }
    if (seen.has(item[key])) throw new Error(`${label} has duplicate ${key}: ${item[key]}`);
    seen.add(item[key]);
  }
}

const products = readCollection('products').sort(byOrder);
const notes = readCollection('notes').sort(byOrder);
const updates = readCollection('updates').sort((a, b) => b.date.localeCompare(a.date));
const socialLinks = readCollection('social-links').sort(byOrder);
uniqueIds(products, 'id', 'products');
uniqueIds(notes, 'id', 'notes');
uniqueIds(socialLinks, 'platform', 'social links');

for (const item of updates) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(item.date) || Number.isNaN(Date.parse(item.date))) {
    throw new Error(`Invalid update date: ${item.date}`);
  }
}

const content = {
  products: products.map(({ published, order, ...item }) => item),
  notes: notes.map(({ published, order, steps, ...item }) => ({
    ...item,
    ...(steps?.length ? { steps: steps.map(({ heading, copy }) => [heading, copy]) } : {})
  })),
  updates: updates.map(({ published, demo, ...item }) => ({
    ...item,
    text: demo ? `【演示】${item.text}` : item.text,
    tags: demo ? [...new Set([...(item.tags || []), '演示数据'])] : item.tags || []
  })),
  socialLinks: socialLinks.map(({ published, order, ...item }) => item)
};

writeFileSync(
  join(root, 'dist', 'content.js'),
  '// Generated by scripts/build-content.mjs from content/*. Do not edit this file.\n' +
    `window.JINCHUAN_CONTENT = ${JSON.stringify(content, null, 2)};\n`
);
console.log(`Built ${products.length} products, ${notes.length} notes, ${updates.length} updates, ${socialLinks.length} social links.`);
